
version: "3.7"
services:
    db:
      image: postgres
      environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: dbartesana
      volumes:
        - ./pgdata:/var/lib/postgresql/dbartesana
      ports:
        - '5432:5432'
    web:
      image: stripe-example-multi-stage
      depends_on:
        - db
      ports:
        - "4000:4000"